language: php
php:
  - hhvm
  - hhvm-nightly
env:
  - HHVM_FLAGS="-vEval.Jit=1"
  - HHVM_FLAGS="-vEval.Jit=0"

before_install:
  - composer self-update --quiet --no-interaction

before_script:
  - composer install --quiet --no-interaction

script: ./.travis/build.sh
